/* FORGE·X — G-code 解析器（纯逻辑，node 可测；不得引用 DOM 或 THREE）

   这是让本项目从「玩具」变成「能验证你自己打印任务的工具」的一步：
   把 Cura / PrusaSlicer / OrcaSlicer 切出来的真实 G-code 导进来，
   在仿真器里重放路径、重算统计量，并**与切片器自己声称的数字对账**。

   为什么这件事有价值：
   切片器给的预估时间众所周知不准（不同切片器对同一份模型能差 30%）。
   这里按 G-code 里真实的 F（进给速度）与位移逐段重算，
   再和文件头里 `;TIME:` / `;Filament used:` 这类自报数字并列展示——
   两个数差多少，本身就是有用的信息。

   ★ 关键设计：**产出结构与 FXSlicer.slice() 完全同构**。
   于是既有的 3D 路径预览、逐层动画、导出、质量评估全都不用改一行就能吃真实 G-code。
   如果为导入功能另造一套数据结构，就要在渲染层到处写 if 分支——那是技术债的经典来源。

   ★ 挤出量用 E 的真实增量，而不是「路径长 × 截面积」的估算。
   这是导入数据相对自产切片的优势所在，别在解析时把它丢掉。 */
(function (root) {
  "use strict";

  var P = {};

  /** 防御性上限：真实 G-code 可以有几百万行，浏览器里得有个头 */
  P.MAX_BYTES = 64 * 1024 * 1024;
  P.MAX_LINES = 4000000;

  /** ⌀1.75 耗材横截面积（mm²），E 值换算体积用 */
  P.FILAMENT_AREA_175 = Math.PI * 0.875 * 0.875;

  /**
   * 各切片器的路径类型注释 → 本项目的统一类型。
   * Cura 用 `;TYPE:WALL-OUTER`，PrusaSlicer/Orca 用 `;TYPE:External perimeter`，
   * 词面不同但语义一致，收敛到一处以免渲染层认不出。
   */
  var TYPE_MAP = [
    [/wall-outer|external perimeter|outer wall/i, "perimeter"],
    [/wall-inner|^perimeter|inner wall|overhang perimeter/i, "perimeter"],
    [/skin|solid infill|top solid|bottom surface|top surface/i, "solid"],
    [/support/i, "support"],
    [/skirt|brim/i, "skirt"],
    [/fill|infill|internal infill|sparse/i, "infill"],
  ];

  function mapType(raw) {
    var s = String(raw || "").trim();
    for (var i = 0; i < TYPE_MAP.length; i++) {
      if (TYPE_MAP[i][0].test(s)) return TYPE_MAP[i][1];
    }
    return "infill"; // 认不出的一律按填充渲染，不猜也不丢
  }

  /** 从注释里抽切片器自报的数字，用于和我们重算的结果对账 */
  var CLAIM_PATTERNS = [
    { key: "timeSec", re: /^;\s*TIME\s*:\s*([\d.]+)/i, scale: 1 },
    { key: "timeSec", re: /^;\s*estimated printing time.*?=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i, parse: "duration" },
    { key: "filamentMm", re: /^;\s*Filament\s+used\s*:\s*([\d.]+)m/i, scale: 1000 },
    { key: "filamentMm", re: /^;\s*filament\s+used\s*\[mm\]\s*=\s*([\d.]+)/i, scale: 1 },
    { key: "filamentG", re: /^;\s*filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i, scale: 1 },
    { key: "layerHeightMm", re: /^;\s*(?:Layer height|layer_height)\s*[:=]\s*([\d.]+)/i, scale: 1 },
    { key: "firmware", re: /^;\s*FLAVOR\s*:\s*(.+)$/i, text: true },
    { key: "slicer", re: /^;\s*(?:generated by|Generated with)\s+(.+)$/i, text: true },
    { key: "slicer", re: /^;\s*(Cura_SteamEngine|PrusaSlicer|OrcaSlicer|SuperSlicer|Simplify3D)[^\n]*/i, text: true },
  ];

  function readClaims(line, claims) {
    for (var i = 0; i < CLAIM_PATTERNS.length; i++) {
      var c = CLAIM_PATTERNS[i];
      var m = c.re.exec(line);
      if (!m) continue;
      if (c.text) {
        if (!claims[c.key]) claims[c.key] = m[1].trim().slice(0, 60);
      } else if (c.parse === "duration") {
        var sec = (+m[1] || 0) * 86400 + (+m[2] || 0) * 3600 + (+m[3] || 0) * 60 + (+m[4] || 0);
        if (sec > 0 && claims.timeSec == null) claims.timeSec = sec;
      } else if (claims[c.key] == null) {
        var v = parseFloat(m[1]);
        if (isFinite(v)) claims[c.key] = v * (c.scale || 1);
      }
      return;
    }
  }

  /** 取一行里的字母参数值，如 word("G1 X10 Y2", "X") → 10 */
  function word(line, letter) {
    var i = line.indexOf(letter);
    while (i >= 0) {
      // 必须是记号开头（前一个字符是空白或行首），避免把 "X" 从注释里挖出来
      if (i === 0 || line.charCodeAt(i - 1) === 32 || line.charCodeAt(i - 1) === 9) {
        var v = parseFloat(line.slice(i + 1));
        if (isFinite(v)) return v;
      }
      i = line.indexOf(letter, i + 1);
    }
    return null;
  }

  /**
   * 解析 G-code 文本 → 与 FXSlicer.slice() 同构的结构。
   *
   * @param text G-code 全文
   * @param opt.densityG   材料密度（g/cm³），用于换算克重；默认 PLA 1.24
   * @param opt.bedSize    打印床尺寸（mm），用于居中坐标；默认 256
   * @param opt.origin     "corner"（默认）或 "center"（Delta 等中心原点机型）
   * @returns {{layers, totalLayers, height, stats, claims, warnings, source}}
   *          解析不出任何挤出路径时抛错——空结果比报错更难排查
   */
  P.parse = function (text, opt) {
    opt = opt || {};
    var src = String(text || "");
    if (src.length > P.MAX_BYTES) {
      throw new Error("G-code 超过 " + Math.round(P.MAX_BYTES / 1024 / 1024) + "MB，请先精简");
    }

    var bed = opt.bedSize || 256;
    var half = bed / 2;
    var offset = opt.origin === "center" ? 0 : half;
    var densityG = opt.densityG || 1.24;

    var lines = src.split(/\r\n|\n|\r/);
    if (lines.length > P.MAX_LINES) throw new Error("G-code 行数超过上限（" + P.MAX_LINES + "）");

    /* 机器状态 */
    var absXYZ = true, absE = true;
    var x = 0, y = 0, z = 0, e = 0, f = 1200;
    var homed = false;

    /* 累积结果 */
    var layers = [];
    var cur = null;            // 当前层 {z, paths, ...}
    var curPath = null;        // 当前连续挤出段
    var curType = "infill";
    var pendingType = null;
    var claims = {};
    var warnings = [];

    var totalExtMm = 0;        // 挤出移动的 XY 位移合计
    var totalTravelMm = 0;
    var totalTimeSec = 0;
    var totalFilamentMm = 0;   // E 的真实增量合计（**精确值**，非估算）
    var minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
    var arcCount = 0;

    function startLayer(zv) {
      closePath();
      cur = { z: zv, paths: [], extLen: 0, travelLen: 0, timeSec: 0 };
      layers.push(cur);
    }

    function closePath() {
      if (curPath && curPath.pts.length >= 2) {
        curPath.len = pathLen(curPath.pts);
        cur.paths.push(curPath);
      }
      curPath = null;
    }

    function pathLen(pts) {
      var L = 0;
      for (var i = 1; i < pts.length; i++) {
        L += Math.hypot(pts[i].x - pts[i - 1].x, pts[i].y - pts[i - 1].y);
      }
      return L;
    }

    for (var li = 0; li < lines.length; li++) {
      var raw = lines[li];
      if (!raw) continue;
      var line = raw.trim();
      if (!line) continue;

      if (line.charCodeAt(0) === 59) {          // ';' 注释行
        readClaims(line, claims);
        var t = /^;\s*TYPE\s*:\s*(.+)$/i.exec(line);
        if (t) pendingType = mapType(t[1]);
        // `;LAYER:` 只作为提示；真正的分层依据是挤出态下的 Z 变化（更普适）
        continue;
      }

      // 去掉行内注释
      var semi = line.indexOf(";");
      if (semi >= 0) {
        var inlineComment = line.slice(semi);
        var ct = /;\s*TYPE\s*:\s*(.+)$/i.exec(inlineComment);
        if (ct) pendingType = mapType(ct[1]);
        line = line.slice(0, semi).trim();
        if (!line) continue;
      }

      var g = /^G(\d+)/i.exec(line);
      if (g) {
        var code = +g[1];

        if (code === 90) { absXYZ = true; continue; }
        if (code === 91) { absXYZ = false; continue; }
        if (code === 92) {                     // 设置当前位置（常用于 E 归零）
          var ge = word(line, "E");
          if (ge != null) e = ge;
          var gx = word(line, "X"); if (gx != null) x = gx;
          var gy = word(line, "Y"); if (gy != null) y = gy;
          var gz = word(line, "Z"); if (gz != null) z = gz;
          continue;
        }
        if (code === 28) {                     // 归位
          homed = true;
          x = 0; y = 0; z = 0;
          closePath();
          continue;
        }
        if (code === 2 || code === 3) {
          // 圆弧插补：本解析器按直线段近似端点，弧长会略短。
          // 真实切片器很少默认输出 G2/G3，遇到时如实警告而不是假装支持。
          arcCount++;
        }
        if (code !== 0 && code !== 1 && code !== 2 && code !== 3) continue;

        var nx = word(line, "X"), ny = word(line, "Y"), nz = word(line, "Z");
        var ne = word(line, "E"), nf = word(line, "F");
        if (nf != null && nf > 0) f = nf;

        var px = x, py = y;
        if (nx != null) x = absXYZ ? nx : x + nx;
        if (ny != null) y = absXYZ ? ny : y + ny;
        if (nz != null) z = absXYZ ? nz : z + nz;

        var de = 0;
        if (ne != null) {
          de = absE ? ne - e : ne;
          e = absE ? ne : e + ne;
        }

        var dist = Math.hypot(x - px, y - py);
        var speed = f / 60;                    // F 是 mm/min，内部统一 mm/s
        if (speed <= 0) speed = 20;

        // E 的增量无条件累计——挤出、回抽、回填都是 E 的真实变化。
        // 曾经只在空驶分支里计负值，结果「回抽记账、回填不记账」，
        // 每次空驶凭空吃掉一段耗材：一个几百次空驶的模型能少算 80% 的用料。
        totalFilamentMm += de;

        if (de > 1e-9 && dist > 1e-6) {
          /* 挤出移动 */
          if (!cur || Math.abs(cur.z - z) > 1e-6) startLayer(z);
          if (!curPath || curPath.type !== (pendingType || curType)) {
            closePath();
            curType = pendingType || curType;
            curPath = { pts: [{ x: px - offset, y: py - offset }], type: curType, speed: speed, filamentMm: 0 };
          }
          curPath.pts.push({ x: x - offset, y: y - offset });
          curPath.speed = speed;
          curPath.filamentMm += de;

          totalExtMm += dist;
          totalTimeSec += dist / speed;
          cur.extLen += dist;
          cur.timeSec += dist / speed;

          // 线段两端都要计入：只记终点的话，「从 (0,0) 挤到 (400,400)」
          // 会得到跨度 0，越界检查形同虚设
          if (px < minX) minX = px; if (px > maxX) maxX = px;
          if (py < minY) minY = py; if (py > maxY) maxY = py;
          if (x < minX) minX = x; if (x > maxX) maxX = x;
          if (y < minY) minY = y; if (y > maxY) maxY = y;
        } else {
          /* 空驶 / 回抽 / 抬升 */
          closePath();
          if (dist > 1e-6) {
            totalTravelMm += dist;
            totalTimeSec += dist / speed;
            if (cur) { cur.travelLen += dist; cur.timeSec += dist / speed; }
          }
        }
        continue;
      }

      var m = /^M(\d+)/i.exec(line);
      if (m) {
        var mc = +m[1];
        if (mc === 82) absE = true;
        else if (mc === 83) absE = false;
        else if (mc === 104 || mc === 109) {
          var s1 = word(line, "S");
          if (s1 != null && claims.nozzleTemp == null) claims.nozzleTemp = s1;
        } else if (mc === 140 || mc === 190) {
          var s2 = word(line, "S");
          if (s2 != null && claims.bedTemp == null) claims.bedTemp = s2;
        }
      }
    }
    closePath();

    /* 收尾：丢掉没有任何路径的空层（抬升/换料常制造这种层） */
    layers = layers.filter(function (L) { return L.paths.length > 0; });
    if (!layers.length) {
      throw new Error("未解析到任何挤出路径 —— 请确认这是 FDM 打印机的 G-code");
    }
    layers.sort(function (a, b) { return a.z - b.z; });

    /* 统计。挤出体积用 E 的真实增量换算，不是「路径长 × 截面积」的估算——
       这是导入真实 G-code 相对自产切片的核心优势。 */
    var volumeMm3 = Math.max(0, totalFilamentMm) * P.FILAMENT_AREA_175;
    var height = layers[layers.length - 1].z;

    if (!homed) warnings.push("文件中没有 G28 归位指令，坐标可能不是绝对机床坐标");
    if (arcCount) warnings.push("含 " + arcCount + " 条圆弧指令（G2/G3），已按直线段近似，弧长略偏小");
    var cMinX = minX - offset, cMaxX = maxX - offset;
    var cMinY = minY - offset, cMaxY = maxY - offset;
    if (cMinX < -half || cMaxX > half || cMinY < -half || cMaxY > half) {
      warnings.push("模型尺寸超出 " + bed + "mm 打印床，路径预览可能溢出");
    }
    if (layers.length < 2) warnings.push("只解析到 1 层，请确认文件完整");

    return {
      layers: layers,
      totalLayers: layers.length,
      height: height,
      stats: {
        extLenMm: totalExtMm,
        travelMm: totalTravelMm,
        timeSec: totalTimeSec,
        volumeCm3: volumeMm3 / 1000,
        filamentM: Math.max(0, totalFilamentMm) / 1000,
        filamentG: (volumeMm3 / 1000) * densityG,
      },
      // 切片器自报的数字，供对账；解析不到就是 undefined，不编造
      claims: claims,
      warnings: warnings,
      bounds: { minX: cMinX, maxX: cMaxX, minY: cMinY, maxY: cMaxY },
      coordinateOrigin: opt.origin === "center" ? "center" : "corner",
      source: "gcode-import",
    };
  };

  /**
   * 与切片器自报数字对账。
   *
   * 这是导入功能真正有用的地方：切片器的时间预估众所周知不准，
   * 不同切片器对同一份模型能差 30%。把两个数并排放出来，差多少本身就是信息。
   * 对不上时**不下判断谁对**——我们的重算也只是另一个模型，不是真值。
   */
  P.reconcile = function (parsed) {
    var out = [];
    var c = parsed.claims || {};
    var s = parsed.stats;

    if (c.timeSec != null) {
      out.push(diff("打印时长", c.timeSec, s.timeSec, "秒", 0.15,
        "切片器会计入加速度与换层开销，本解析器按匀速估算，偏短属正常"));
    }
    if (c.filamentMm != null) {
      out.push(diff("耗材长度", c.filamentMm, s.filamentM * 1000, "mm", 0.02,
        "两者都来自 E 值，差异应当很小；偏大说明解析漏掉了某些挤出段"));
    }
    if (c.filamentG != null) {
      out.push(diff("耗材克重", c.filamentG, s.filamentG, "g", 0.05,
        "依赖材料密度设置，密度不同会直接体现在这里"));
    }
    return out;
  };

  function diff(name, claimed, computed, unit, tol, note) {
    var rel = claimed > 0 ? Math.abs(computed - claimed) / claimed : 0;
    return {
      name: name,
      claimed: claimed,
      computed: computed,
      unit: unit,
      relDiff: rel,
      agrees: rel <= tol,
      note: note,
    };
  }

  /** 秒 → 人类可读，供对账表展示 */
  P.fmtSec = function (sec) {
    if (!isFinite(sec) || sec < 0) return "—";
    var h = Math.floor(sec / 3600);
    var m = Math.round((sec % 3600) / 60);
    return h > 0 ? h + " 小时 " + String(m).padStart(2, "0") + " 分" : m + " 分钟";
  };

  root.FXGcodeParser = P;
})(typeof window !== "undefined" ? window : globalThis);
