/* FORGE·X — G-code 解析器（纯逻辑；不得引用 DOM 或 THREE）。
   自 js/gcode-parser.js 机械迁移：算法逐行保留，仅换模块壳并加类型。

   ★ 关键设计：产出结构与切片器 slice() 完全同构——既有的 3D 路径预览、
   逐层动画、导出、质量评估全都不用改一行就能吃真实 G-code。
   ★ 挤出量用 E 的真实增量，而不是「路径长 × 截面积」的估算。 */
import type { Point2 } from "./util.ts";

/** 防御性上限：真实 G-code 可以有几百万行，浏览器里得有个头 */
export const MAX_BYTES = 64 * 1024 * 1024;
export const MAX_LINES = 4000000;

/** ⌀1.75 耗材横截面积（mm²），E 值换算体积用 */
export const FILAMENT_AREA_175 = Math.PI * 0.875 * 0.875;

export interface GcodePath {
  pts: Point2[];
  type: string;
  speed: number;
  filamentMm: number;
  len?: number;
}

export interface GcodeLayer {
  z: number;
  paths: GcodePath[];
  extLen: number;
  travelLen: number;
  timeSec: number;
}

export interface GcodeClaims {
  timeSec?: number;
  filamentMm?: number;
  filamentG?: number;
  layerHeightMm?: number;
  firmware?: string;
  slicer?: string;
  nozzleTemp?: number;
  bedTemp?: number;
  [key: string]: number | string | undefined;
}

export interface ParsedGcodeResult {
  layers: GcodeLayer[];
  totalLayers: number;
  height: number;
  stats: {
    extLenMm: number;
    travelMm: number;
    timeSec: number;
    volumeCm3: number;
    filamentM: number;
    filamentG: number;
  };
  claims: GcodeClaims;
  warnings: string[];
  bounds: { minX: number; maxX: number; minY: number; maxY: number };
  coordinateOrigin: "corner" | "center";
  source: string;
  sha256?: string;
}

export interface GcodeParserOptions {
  densityG?: number;
  bedSize?: number;
  origin?: "corner" | "center" | string;
}

export interface ReconcileRow {
  name: string;
  claimed: number;
  computed: number;
  unit: string;
  relDiff: number;
  agrees: boolean;
  note: string;
}

/** 对原始 G-code 字节计算 SHA-256；用于与真机日志声明的摘要建立责任链。 */
export function sha256(input: string | ArrayBuffer | ArrayBufferView): Promise<string> {
  const webCrypto = (globalThis as { crypto?: Crypto }).crypto;
  if (!webCrypto || !webCrypto.subtle) return Promise.reject(new Error("当前运行环境不支持 SHA-256 校验"));
  let bytes: Uint8Array;
  if (typeof input === "string") bytes = new TextEncoder().encode(input);
  else if (input instanceof ArrayBuffer) bytes = new Uint8Array(input);
  else if (ArrayBuffer.isView(input)) bytes = new Uint8Array(input.buffer, input.byteOffset, input.byteLength);
  else return Promise.reject(new Error("SHA-256 输入必须是文本或字节数据"));
  const exact = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  return webCrypto.subtle.digest("SHA-256", exact).then((digest) =>
    Array.from(new Uint8Array(digest))
      .map((v) => v.toString(16).padStart(2, "0"))
      .join("")
  );
}

/**
 * 各切片器的路径类型注释 → 本项目的统一类型。
 * Cura 用 `;TYPE:WALL-OUTER`，PrusaSlicer/Orca 用 `;TYPE:External perimeter`，
 * 词面不同但语义一致，收敛到一处以免渲染层认不出。
 */
const TYPE_MAP: Array<[RegExp, string]> = [
  [/wall-outer|external perimeter|outer wall/i, "perimeter"],
  [/wall-inner|^perimeter|inner wall|overhang perimeter/i, "perimeter"],
  [/skin|solid infill|top solid|bottom surface|top surface/i, "solid"],
  [/support/i, "support"],
  [/skirt|brim/i, "skirt"],
  [/fill|infill|internal infill|sparse/i, "infill"],
];

function mapType(raw: unknown): string {
  const s = String(raw || "").trim();
  for (let i = 0; i < TYPE_MAP.length; i++) {
    if (TYPE_MAP[i]![0].test(s)) return TYPE_MAP[i]![1];
  }
  return "infill"; // 认不出的一律按填充渲染，不猜也不丢
}

/** 从注释里抽切片器自报的数字，用于和我们重算的结果对账 */
interface ClaimPattern {
  key: string;
  re: RegExp;
  scale?: number;
  parse?: string;
  text?: boolean;
}
const CLAIM_PATTERNS: ClaimPattern[] = [
  { key: "timeSec", re: /^;\s*TIME\s*:\s*([\d.]+)/i, scale: 1 },
  {
    key: "timeSec",
    re: /^;\s*estimated printing time.*?=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i,
    parse: "duration",
  },
  { key: "filamentMm", re: /^;\s*Filament\s+used\s*:\s*([\d.]+)m/i, scale: 1000 },
  { key: "filamentMm", re: /^;\s*filament\s+used\s*\[mm\]\s*=\s*([\d.]+)/i, scale: 1 },
  { key: "filamentG", re: /^;\s*filament\s+used\s*\[g\]\s*=\s*([\d.]+)/i, scale: 1 },
  { key: "layerHeightMm", re: /^;\s*(?:Layer height|layer_height)\s*[:=]\s*([\d.]+)/i, scale: 1 },
  { key: "firmware", re: /^;\s*FLAVOR\s*:\s*(.+)$/i, text: true },
  { key: "slicer", re: /^;\s*(?:generated by|Generated with)\s+(.+)$/i, text: true },
  { key: "slicer", re: /^;\s*(Cura_SteamEngine|PrusaSlicer|OrcaSlicer|SuperSlicer|Simplify3D)[^\n]*/i, text: true },
];

function readClaims(line: string, claims: GcodeClaims): void {
  for (let i = 0; i < CLAIM_PATTERNS.length; i++) {
    const c = CLAIM_PATTERNS[i]!;
    const m = c.re.exec(line);
    if (!m) continue;
    if (c.text) {
      if (!claims[c.key]) claims[c.key] = m[1]!.trim().slice(0, 60);
    } else if (c.parse === "duration") {
      const sec =
        (+(m[1] ?? 0) || 0) * 86400 + (+(m[2] ?? 0) || 0) * 3600 + (+(m[3] ?? 0) || 0) * 60 + (+(m[4] ?? 0) || 0);
      if (sec > 0 && claims.timeSec == null) claims.timeSec = sec;
    } else if (claims[c.key] == null) {
      const v = parseFloat(m[1]!);
      if (isFinite(v)) claims[c.key] = v * (c.scale || 1);
    }
    return;
  }
}

/** 取一行里的字母参数值，如 word("G1 X10 Y2", "X") → 10 */
function word(line: string, letter: string): number | null {
  let i = line.indexOf(letter);
  while (i >= 0) {
    // 必须是记号开头（前一个字符是空白或行首），避免把 "X" 从注释里挖出来
    if (i === 0 || line.charCodeAt(i - 1) === 32 || line.charCodeAt(i - 1) === 9) {
      const v = parseFloat(line.slice(i + 1));
      if (isFinite(v)) return v;
    }
    i = line.indexOf(letter, i + 1);
  }
  return null;
}

export interface IncrementalParser {
  push(textChunk: string): IncrementalParser;
  finish(): ParsedGcodeResult;
}

/**
 * 创建增量解析器。调用方可以逐块解码大文件，而不必先把全文拼成一个字符串；
 * 内部只保留尚未结束的当前行，CRLF 即使横跨两个 chunk 也只计一个换行。
 */
export function createIncrementalParser(opt?: GcodeParserOptions): IncrementalParser {
  opt = opt || {};
  const bed = opt.bedSize || 256;
  const half = bed / 2;
  const offset = opt.origin === "center" ? 0 : half;
  const densityG = opt.densityG || 1.24;

  /* 机器状态 */
  let absXYZ = true,
    absE = true;
  let x = 0,
    y = 0,
    z = 0,
    e = 0,
    f = 1200;
  let homed = false;

  /* 累积结果 */
  let layers: GcodeLayer[] = [];
  let cur: GcodeLayer | null = null; // 当前层
  let curPath: GcodePath | null = null; // 当前连续挤出段
  let curType = "infill";
  let pendingType: string | null = null;
  const claims: GcodeClaims = {};
  const warnings: string[] = [];

  let totalExtMm = 0; // 挤出移动的 XY 位移合计
  let totalTravelMm = 0;
  let totalTimeSec = 0;
  let totalFilamentMm = 0; // E 的真实增量合计（精确值，非估算）
  let minX = Infinity,
    maxX = -Infinity,
    minY = Infinity,
    maxY = -Infinity;
  let arcCount = 0;

  /* 流式输入状态。lineCount 从 1 开始，与旧实现 split(...).length 完全一致。 */
  let lineBuffer = "";
  let pendingCR = false;
  let lineCount = 1;
  let inputLength = 0;
  let finished = false;
  let result: ParsedGcodeResult | null = null;
  let finishError: Error | null = null;

  function startLayer(zv: number): void {
    closePath();
    cur = { z: zv, paths: [], extLen: 0, travelLen: 0, timeSec: 0 };
    layers.push(cur);
  }

  function closePath(): void {
    if (curPath && curPath.pts.length >= 2) {
      curPath.len = pathLen(curPath.pts);
      cur!.paths.push(curPath);
    }
    curPath = null;
  }

  function pathLen(pts: Point2[]): number {
    let L = 0;
    for (let i = 1; i < pts.length; i++) {
      L += Math.hypot(pts[i]!.x - pts[i - 1]!.x, pts[i]!.y - pts[i - 1]!.y);
    }
    return L;
  }

  function processLine(raw: string): void {
    if (!raw) return;
    let line = raw.trim();
    if (!line) return;

    if (line.charCodeAt(0) === 59) {
      // ';' 注释行
      readClaims(line, claims);
      const t = /^;\s*TYPE\s*:\s*(.+)$/i.exec(line);
      if (t) pendingType = mapType(t[1]);
      // `;LAYER:` 只作为提示；真正的分层依据是挤出态下的 Z 变化（更普适）
      return;
    }

    // 去掉行内注释
    const semi = line.indexOf(";");
    if (semi >= 0) {
      const inlineComment = line.slice(semi);
      const ct = /;\s*TYPE\s*:\s*(.+)$/i.exec(inlineComment);
      if (ct) pendingType = mapType(ct[1]);
      line = line.slice(0, semi).trim();
      if (!line) return;
    }

    const g = /^G(\d+)/i.exec(line);
    if (g) {
      const code = +g[1]!;

      if (code === 90) {
        absXYZ = true;
        return;
      }
      if (code === 91) {
        absXYZ = false;
        return;
      }
      if (code === 92) {
        // 设置当前位置（常用于 E 归零）
        const ge = word(line, "E");
        if (ge != null) e = ge;
        const gx = word(line, "X");
        if (gx != null) x = gx;
        const gy = word(line, "Y");
        if (gy != null) y = gy;
        const gz = word(line, "Z");
        if (gz != null) z = gz;
        return;
      }
      if (code === 28) {
        // 归位
        homed = true;
        x = 0;
        y = 0;
        z = 0;
        closePath();
        return;
      }
      if (code === 2 || code === 3) {
        // 圆弧插补：本解析器按直线段近似端点，弧长会略短。
        arcCount++;
      }
      if (code !== 0 && code !== 1 && code !== 2 && code !== 3) return;

      const nx = word(line, "X"),
        ny = word(line, "Y"),
        nz = word(line, "Z");
      const ne = word(line, "E"),
        nf = word(line, "F");
      if (nf != null && nf > 0) f = nf;

      const px = x,
        py = y;
      if (nx != null) x = absXYZ ? nx : x + nx;
      if (ny != null) y = absXYZ ? ny : y + ny;
      if (nz != null) z = absXYZ ? nz : z + nz;

      let de = 0;
      if (ne != null) {
        de = absE ? ne - e : ne;
        e = absE ? ne : e + ne;
      }

      const dist = Math.hypot(x - px, y - py);
      let speed = f / 60; // F 是 mm/min，内部统一 mm/s
      if (speed <= 0) speed = 20;

      // E 的增量无条件累计——挤出、回抽、回填都是 E 的真实变化。
      totalFilamentMm += de;

      if (de > 1e-9 && dist > 1e-6) {
        /* 挤出移动 */
        if (!cur || Math.abs(cur.z - z) > 1e-6) startLayer(z);
        if (!curPath || curPath.type !== (pendingType || curType)) {
          closePath();
          curType = pendingType || curType;
          curPath = { pts: [{ x: px - offset, y: py - offset }], type: curType, speed, filamentMm: 0 };
        }
        curPath.pts.push({ x: x - offset, y: y - offset });
        curPath.speed = speed;
        curPath.filamentMm += de;

        totalExtMm += dist;
        totalTimeSec += dist / speed;
        cur!.extLen += dist;
        cur!.timeSec += dist / speed;

        // 线段两端都要计入：只记终点的话，「从 (0,0) 挤到 (400,400)」
        // 会得到跨度 0，越界检查形同虚设
        if (px < minX) minX = px;
        if (px > maxX) maxX = px;
        if (py < minY) minY = py;
        if (py > maxY) maxY = py;
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      } else {
        /* 空驶 / 回抽 / 抬升 */
        closePath();
        if (dist > 1e-6) {
          totalTravelMm += dist;
          totalTimeSec += dist / speed;
          if (cur) {
            cur.travelLen += dist;
            cur.timeSec += dist / speed;
          }
        }
      }
      return;
    }

    const m = /^M(\d+)/i.exec(line);
    if (m) {
      const mc = +m[1]!;
      if (mc === 82) absE = true;
      else if (mc === 83) absE = false;
      else if (mc === 104 || mc === 109) {
        const s1 = word(line, "S");
        if (s1 != null && claims.nozzleTemp == null) claims.nozzleTemp = s1;
      } else if (mc === 140 || mc === 190) {
        const s2 = word(line, "S");
        if (s2 != null && claims.bedTemp == null) claims.bedTemp = s2;
      }
    }
  }

  function tooManyLines(): Error {
    return new Error("G-code 行数超过上限（" + MAX_LINES + "）");
  }

  function emitLineBreak(): void {
    processLine(lineBuffer);
    lineBuffer = "";
    lineCount++;
    if (lineCount > MAX_LINES) throw tooManyLines();
  }

  function consumeChunk(chunk: string): void {
    let i = 0;
    let start = 0;

    /* 上一个 chunk 以 CR 结束：先确认本块开头是否是配对的 LF。 */
    if (pendingCR && chunk.length) {
      pendingCR = false;
      emitLineBreak();
      if (chunk.charCodeAt(0) === 10) {
        i = 1;
        start = 1;
      }
    }

    for (; i < chunk.length; i++) {
      const ch = chunk.charCodeAt(i);
      if (ch === 13) {
        lineBuffer += chunk.slice(start, i);
        if (i + 1 < chunk.length) {
          if (chunk.charCodeAt(i + 1) === 10) i++;
          emitLineBreak();
          start = i + 1;
        } else {
          pendingCR = true;
          start = chunk.length;
        }
      } else if (ch === 10) {
        lineBuffer += chunk.slice(start, i);
        emitLineBreak();
        start = i + 1;
      }
    }

    if (start < chunk.length) lineBuffer += chunk.slice(start);
  }

  function finalize(): ParsedGcodeResult {
    if (pendingCR) {
      pendingCR = false;
      emitLineBreak();
    }
    /* split() 总会产生最后一个字段；即使文件以换行结尾，也处理对应的空行。 */
    processLine(lineBuffer);
    lineBuffer = "";
    closePath();

    /* 收尾：丢掉没有任何路径的空层（抬升/换料常制造这种层） */
    layers = layers.filter((L) => L.paths.length > 0);
    if (!layers.length) {
      throw new Error("未解析到任何挤出路径 —— 请确认这是 FDM 打印机的 G-code");
    }
    layers.sort((a, b) => a.z - b.z);

    /* 统计。挤出体积用 E 的真实增量换算，不是「路径长 × 截面积」的估算。 */
    const volumeMm3 = Math.max(0, totalFilamentMm) * FILAMENT_AREA_175;
    const height = layers[layers.length - 1]!.z;

    if (!homed) warnings.push("文件中没有 G28 归位指令，坐标可能不是绝对机床坐标");
    if (arcCount) warnings.push("含 " + arcCount + " 条圆弧指令（G2/G3），已按直线段近似，弧长略偏小");
    const cMinX = minX - offset,
      cMaxX = maxX - offset;
    const cMinY = minY - offset,
      cMaxY = maxY - offset;
    if (cMinX < -half || cMaxX > half || cMinY < -half || cMaxY > half) {
      warnings.push("模型尺寸超出 " + bed + "mm 打印床，路径预览可能溢出");
    }
    if (layers.length < 2) warnings.push("只解析到 1 层，请确认文件完整");

    return {
      layers,
      totalLayers: layers.length,
      height,
      stats: {
        extLenMm: totalExtMm,
        travelMm: totalTravelMm,
        timeSec: totalTimeSec,
        volumeCm3: volumeMm3 / 1000,
        filamentM: Math.max(0, totalFilamentMm) / 1000,
        filamentG: (volumeMm3 / 1000) * densityG,
      },
      // 切片器自报的数字，供对账；解析不到就是 undefined，不编造
      claims,
      warnings,
      bounds: { minX: cMinX, maxX: cMaxX, minY: cMinY, maxY: cMaxY },
      coordinateOrigin: opt!.origin === "center" ? "center" : "corner",
      source: "gcode-import",
    };
  }

  const api: IncrementalParser = {
    push(textChunk: string) {
      if (finished) throw new Error("增量 G-code 解析已经结束");
      if (typeof textChunk !== "string") throw new TypeError("G-code chunk 必须是文本");
      inputLength += textChunk.length;
      if (inputLength > MAX_BYTES) {
        throw new Error("G-code 超过 " + Math.round(MAX_BYTES / 1024 / 1024) + "MB，请先精简");
      }
      if (textChunk.length) consumeChunk(textChunk);
      return api;
    },
    finish() {
      if (finished) {
        if (finishError) throw finishError;
        return result!;
      }
      finished = true;
      try {
        result = finalize();
        return result;
      } catch (err) {
        finishError = err as Error;
        throw err;
      }
    },
  };
  return api;
}

/**
 * 解析 G-code 全文 → 与切片器 slice() 同构的结构。
 * 全量入口与增量入口共用同一状态机，避免两套实现发生语义漂移。
 */
export function parse(text: string, opt?: GcodeParserOptions): ParsedGcodeResult {
  const parser = createIncrementalParser(opt);
  parser.push(String(text || ""));
  return parser.finish();
}

/**
 * 与切片器自报数字对账。对不上时不下判断谁对——我们的重算也只是另一个模型，不是真值。
 */
export function reconcile(parsed: ParsedGcodeResult): ReconcileRow[] {
  const out: ReconcileRow[] = [];
  const c = parsed.claims || {};
  const s = parsed.stats;

  if (c.timeSec != null) {
    out.push(
      diff("打印时长", c.timeSec, s.timeSec, "秒", 0.15, "切片器会计入加速度与换层开销，本解析器按匀速估算，偏短属正常")
    );
  }
  if (c.filamentMm != null) {
    out.push(
      diff(
        "耗材长度",
        c.filamentMm,
        s.filamentM * 1000,
        "mm",
        0.02,
        "两者都来自 E 值，差异应当很小；偏大说明解析漏掉了某些挤出段"
      )
    );
  }
  if (c.filamentG != null) {
    out.push(diff("耗材克重", c.filamentG, s.filamentG, "g", 0.05, "依赖材料密度设置，密度不同会直接体现在这里"));
  }
  return out;
}

function diff(name: string, claimed: number, computed: number, unit: string, tol: number, note: string): ReconcileRow {
  const rel = claimed > 0 ? Math.abs(computed - claimed) / claimed : 0;
  return {
    name,
    claimed,
    computed,
    unit,
    relDiff: rel,
    agrees: rel <= tol,
    note,
  };
}

/** 秒 → 人类可读，供对账表展示 */
export function fmtSec(sec: number): string {
  if (!isFinite(sec) || sec < 0) return "—";
  const h = Math.floor(sec / 3600);
  const m = Math.round((sec % 3600) / 60);
  return h > 0 ? h + " 小时 " + String(m).padStart(2, "0") + " 分" : m + " 分钟";
}
