/* P6 跨浏览器关键链路：Chromium 全量之外，Firefox/WebKit 也必须能启动与复盘。 */
"use strict";

const { test, expect } = require("@playwright/test");

async function waitBooted(page) {
  await page.waitForFunction(() => window.FX && window.FX.sim && window.FX.sim.slice, null, {
    timeout: 30_000,
  });
}

test.describe("P6 cross-browser contract", () => {
  test("应用启动、WebGL 场景与默认切片可用", async ({ page, browserName }) => {
    await page.goto("/");
    await waitBooted(page);
    await expect(page.locator("#webgl-fallback")).toBeHidden();
    await expect(page.locator("#status-pill")).toContainText("系统就绪");
    const state = await page.evaluate(() => ({
      model: window.FX.sim.model && window.FX.sim.model.id,
      layers: window.FX.sim.slice.totalLayers,
      webgl: !!window.FX.fx.renderer,
    }));
    expect(state.webgl, `${browserName} should create the renderer`).toBe(true);
    expect(state.model).toBe("gear");
    expect(state.layers).toBeGreaterThan(1);
  });

  test("G-code 与真机日志在三种浏览器形成校准观测", async ({ page }) => {
    await page.goto("/");
    await waitBooted(page);
    const gcode = [
      "; generated by OrcaSlicer 2.2.0",
      "M83",
      "G90",
      "G28",
      "G1 Z0.20 F600",
      "G0 X20 Y20 F6000",
      ";TYPE:Outer wall",
      "G1 X80 Y20 E1 F600",
      "G1 X80 Y80 E1",
    ].join("\n");
    await page.locator("#gcode-input").setInputFiles({
      name: "cross-browser.gcode",
      mimeType: "text/x-gcode",
      buffer: Buffer.from(gcode),
    });
    await page.waitForFunction(() => window.FX.sim.importedToolpath);

    await page.locator("#machine-log-input").setInputFiles({
      name: "cross-browser.machine-log.json",
      mimeType: "application/json",
      buffer: Buffer.from(JSON.stringify({
        format: "forgex-machine-log",
        version: 1,
        job: {
          machineId: "FX-CROSS",
          firmware: "Klipper 0.12",
          durationSec: 120,
          completedLayers: 1,
          status: "success",
        },
        telemetry: [],
      })),
    });

    await expect(page.locator("#machine-log-summary")).toContainText("FX-CROSS");
    await expect(page.locator("#machine-log-summary")).toContainText("单任务观测倍率");
    const observation = await page.evaluate(() => window.FX.ui._machineLogState.observation);
    expect(observation.rawRatio).toBeGreaterThan(1);
    expect(observation.note).toContain("至少三个");
  });
});
