/* Stage 10.3「Web Worker 收口」回归卡口（V1 §5.5 / V2 §4.4 工作项 3）。

   固化的结论：G-code 导入的读取/哈希/解析/打包在 Web Worker 内完成，
   主线程在导入期间不出现同步整段解析那种秒级长任务，UI 保持可交互。

   口径说明：
   - 用 16 MiB 合成文件（与 backend GCodeBenchmark 同档），避免在 CI 跑 64 MB 全量；
     64 MB 级全量测量由 tools/gcode-worker-audit.js 手动复跑。
   - 断言用「比例 + 宽裕绝对值」双保险：同步解析 16 MiB 在任何机器上都是
     一条与导入等长的长任务（阻塞占比 ≈ 1），Worker 化后主线程只剩分片装配，
     阻塞占比与单条时长与机器快慢近似无关。 */
/* global PerformanceObserver */
"use strict";

const fs = require("fs");
const os = require("os");
const path = require("path");
const { test, expect } = require("@playwright/test");

/** 与 tools/gcode-worker-audit.js 同构的迷你生成器（周界环 + 之字填充 + 回抽） */
function syntheticGcode(targetBytes) {
  const chunks = [
    [
      ";FLAVOR:Marlin",
      ";TIME:7200",
      ";Filament used: 8.4m",
      ";Layer height: 0.2",
      "; generated by Cura_SteamEngine 5.10 (e2e worker gate fixture)",
      "M104 S210",
      "M140 S60",
      "G28",
      "G90",
      "M82",
      "",
    ].join("\n"),
  ];
  let bytes = chunks[0].length;
  let layer = 0;
  while (bytes < targetBytes) {
    const z = (0.2 * (layer + 1)).toFixed(2);
    const lines = [`;LAYER:${layer}`, "G92 E0", `G0 F9000 X30.000 Y30.000 Z${z}`, ";TYPE:WALL-OUTER"];
    let e = 0;
    for (let i = 1; i <= 64; i++) {
      const angle = (i / 64) * Math.PI * 2;
      e += 0.35;
      lines.push(
        `G1 F1350 X${(128 + 90 * Math.cos(angle)).toFixed(3)} Y${(128 + 90 * Math.sin(angle)).toFixed(3)} E${e.toFixed(4)}`
      );
    }
    lines.push(";TYPE:FILL");
    for (let strip = 0; strip < 60; strip++) {
      const y = (34 + strip * 3.1).toFixed(3);
      e -= 0.8;
      lines.push(`G1 F2700 E${e.toFixed(4)}`);
      lines.push(`G0 F9000 X${strip % 2 === 0 ? "34.000" : "222.000"} Y${y}`);
      e += 0.8;
      lines.push(`G1 F2700 E${e.toFixed(4)}`);
      for (let seg = 1; seg <= 8; seg++) {
        const x = strip % 2 === 0 ? 34 + seg * 23.5 : 222 - seg * 23.5;
        e += 0.6;
        lines.push(`G1 F2400 X${x.toFixed(3)} Y${y} E${e.toFixed(4)}`);
      }
    }
    const block = lines.join("\n") + "\n";
    chunks.push(block);
    bytes += block.length;
    layer += 1;
  }
  return Buffer.from(chunks.join(""), "utf8");
}

test.describe("G-code 导入 Worker 收口", () => {
  test("16 MiB 导入走 Worker：主线程无秒级长任务，UI 保持心跳", async ({ page }) => {
    test.setTimeout(180_000);
    await page.goto("/react");
    await page.waitForFunction(() => window.FX && window.FX.sim && window.FX.sim.slice, null, { timeout: 30_000 });
    await page.locator("#flow-pills .flow-pill").first().click();

    /* 无头环境走 SwiftShader 软渲染：Worker 满载 CPU 时，一帧 three.js 软栅格化
       可被饿成秒级"长任务"（CPU 剖析确认其 self time 全在 (program) 原生栅格化，
       导入 JS 占比毫秒级；真机 GPU 无此噪声）。本卡口度量的是导入链路是否阻塞
       主线程，故停掉绘制调用、保留 rAF 节拍与全部 DOM/React 行为，使长任务
       只反映导入路径自身的 JS。 */
    await page.evaluate(() => {
      window.FX.fx.renderer.render = () => {};
    });

    await page.evaluate(() => {
      const audit = { t0: 0, t1: 0, done: false, longtasks: [], rafT: [], errors: [] };
      window.__gcodeGate = audit;
      const observer = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) audit.longtasks.push({ start: entry.startTime, duration: entry.duration });
      });
      observer.observe({ type: "longtask", buffered: false });
      document.getElementById("gcode-input").addEventListener(
        "change",
        () => {
          audit.t0 = performance.now();
        },
        { once: true, capture: true }
      );
      window.FX.bus.on("sliced", (info) => {
        if (info && info.source === "gcode-import" && !audit.t1) audit.t1 = performance.now();
      });
      window.FX.bus.on("toast", (payload) => {
        if (payload && payload.type === "err") audit.errors.push(String(payload.msg));
      });
      const beat = (t) => {
        audit.rafT.push(t);
        if (!audit.done) requestAnimationFrame(beat);
      };
      requestAnimationFrame(beat);
    });

    /* 落盘后按真实路径导入：与用户从磁盘选文件一致（file-backed Blob 由 IO 线程供给；
       内存 buffer 形式的 File 在部分环境下读取会占用创建线程，污染主线程度量）。 */
    const fixtureDir = fs.mkdtempSync(path.join(os.tmpdir(), "forgex-gcode-gate-"));
    const fixturePath = path.join(fixtureDir, "worker-gate-16mib.gcode");
    fs.writeFileSync(fixturePath, syntheticGcode(16 * 1024 * 1024));
    try {
      await page.locator("#gcode-input").setInputFiles(fixturePath);
      await page.waitForFunction(() => window.__gcodeGate.t1 > 0 && window.FX.sim.importedToolpath, null, {
        timeout: 120_000,
        polling: 250,
      });
      await expect(page.locator("#gcode-summary")).toBeVisible();
      await expect(page.locator("#gcode-summary")).toContainText("层");

      const audit = await page.evaluate(() => {
        const a = window.__gcodeGate;
        a.done = true;
        const windowEnd = a.t1 + 200;
        const inWindow = a.longtasks.filter((e) => e.start + e.duration > a.t0 && e.start < windowEnd);
        const gaps = [];
        for (let i = 1; i < a.rafT.length; i++) {
          if (a.rafT[i] > a.t0 && a.rafT[i - 1] < windowEnd) gaps.push(a.rafT[i] - a.rafT[i - 1]);
        }
        return {
          via: window.__forgexGcodeImportVia,
          importMs: a.t1 - a.t0,
          longtaskMaxMs: inWindow.reduce((max, e) => Math.max(max, e.duration), 0),
          longtaskTotalMs: inWindow.reduce((sum, e) => sum + e.duration, 0),
          longtasks: inWindow,
          rafGapMaxMs: gaps.reduce((max, g) => Math.max(max, g), 0),
          totalLayers: window.FX.sim.slice.totalLayers,
          errors: a.errors,
        };
      });
      console.log("[gcode-worker-gate]", JSON.stringify(audit));

      expect(audit.errors).toEqual([]);
      expect(audit.totalLayers).toBeGreaterThan(50);
      // 解析确实发生在 Worker（回退主线程时此探针为 "main"，应视为回归）
      expect(audit.via).toBe("worker");
      // 主线程健康度：同步解析 16 MiB 是单条 ≥ 秒级长任务、阻塞占比 ≈ 1；
      // Worker 化后仅剩分片装配与挂载，两项都必须显著低于该量级。
      expect(audit.longtaskMaxMs).toBeLessThan(500);
      expect(audit.longtaskTotalMs / audit.importMs).toBeLessThan(0.5);
      // UI 心跳：导入期间 rAF 最长间隔远小于同步路径的整段冻结
      expect(audit.rafGapMaxMs).toBeLessThan(600);
    } finally {
      fs.rmSync(fixtureDir, { recursive: true, force: true });
    }
  });
});
