/* P5 扩展链路：真实 G-code 复盘与声明式 Profile 导入。 */
"use strict";

const { test, expect } = require("@playwright/test");

async function waitBooted(page) {
  await page.waitForFunction(() => window.FX && window.FX.sim && window.FX.sim.slice, null, {
    timeout: 30_000,
  });
}

test.describe("P5 生态扩展", () => {
  test("导入真实 G-code 后生成对账结果与 3D 回放路径", async ({ page }) => {
    await page.goto("/");
    await waitBooted(page);

    const gcode = [
      "; generated by Cura_SteamEngine 5.10",
      ";TIME:120",
      ";Filament used: 0.002m",
      "G21",
      "G90",
      "M83",
      "G28",
      "M104 S215",
      "M140 S60",
      "G1 Z0.20 F720",
      "G0 X120 Y120 F6000",
      ";TYPE:WALL-OUTER",
      "G1 X136 Y120 E1.0 F1200",
      "G1 X136 Y136 E0.5",
      ";LAYER:1",
      "G1 Z0.40 F720",
      "G0 X121 Y121 F6000",
      ";TYPE:FILL",
      "G1 X135 Y135 E0.5 F1800",
    ].join("\n");

    await page.locator("#gcode-input").setInputFiles({
      name: "fixture.gcode",
      mimeType: "text/x-gcode",
      buffer: Buffer.from(gcode),
    });
    await page.waitForFunction(() => window.FX.sim.importedToolpath);

    await expect(page.locator("#gcode-summary")).toContainText("fixture.gcode");
    await expect(page.locator("#gcode-summary")).toContainText("2 层");
    const result = await page.evaluate(() => ({
      source: window.FX.sim.slice.source,
      layers: window.FX.sim.slice.totalLayers,
      origin: window.FX.sim.slice.coordinateOrigin,
      toolpathLayers: window.FX.sim.printer._toolpathLayerRanges.length,
      reconcile: window.FXGcodeParser.reconcile(window.FX.sim.slice).length,
    }));
    expect(result).toEqual({
      source: "gcode-import",
      layers: 2,
      origin: "corner",
      toolpathLayers: 2,
      reconcile: 2,
    });

    await page.locator("#machine-log-input").setInputFiles({
      name: "fixture-machine-log.json",
      mimeType: "application/json",
      buffer: Buffer.from(JSON.stringify({
        format: "forgex-machine-log",
        version: 1,
        job: {
          durationSec: 140,
          filamentMm: 2,
          completedLayers: 2,
          status: "success",
        },
        telemetry: [{ timeSec: 0, nozzleC: 25 }, { timeSec: 140, nozzleC: 214 }],
      })),
    });
    await expect(page.locator("#machine-log-summary")).toContainText("fixture-machine-log.json");
    await expect(page.locator("#machine-log-summary")).toContainText("实测");
  });

  test("导入社区 Profile 后机型与材料即时进入 UI", async ({ page }) => {
    await page.goto("/");
    await waitBooted(page);

    const bundle = {
      format: "forgex-profile-bundle",
      version: 1,
      machines: [
        {
          id: "e2e-corexy-310",
          name: "E2E CoreXY 310",
          tag: "E2E-310",
          kinematics: "corexy",
          description: "E2E fixture · enclosed",
          buildVolume: { x: 310, y: 310, z: 320 },
          enclosed: true,
          source: "Playwright fixture",
        },
      ],
      materials: [
        {
          id: "E2E-MAT",
          name: "E2E Material",
          nozzle: { default: 230, min: 220, max: 240 },
          bed: { default: 70, min: 60 },
          fan: 55,
          densityG: 1.3,
          maxSpeed: 150,
          flowMm3s: 8,
          shrinkage: 0.4,
          priceCnyKg: 120,
          source: "Playwright fixture",
        },
      ],
    };

    await page.locator("#profile-input").setInputFiles({
      name: "e2e-profile.json",
      mimeType: "application/json",
      buffer: Buffer.from(JSON.stringify(bundle)),
    });
    await page.waitForFunction(() => window.FXProfiles.machine("e2e-corexy-310"));

    await expect(page.locator("#ctx-body")).toContainText("E2E CoreXY 310");
    await page.locator("#btn-params").click();
    await expect(page.locator("#param-body .chip", { hasText: "E2E-MAT" })).toBeVisible();

    const imported = await page.evaluate(() => {
      window.FX.sim.setPrinterModel("e2e-corexy-310");
      window.FX.sim.applyMaterial("E2E-MAT");
      return {
        bed: window.FX.sim.printer.BED_SIZE,
        tag: window.FX.sim.printer.MODEL_TAG,
        material: window.FX.sim.settings.material,
        nozzle: window.FX.sim.settings.nozzleTemp,
      };
    });
    expect(imported).toEqual({ bed: 310, tag: "E2E-310", material: "E2E-MAT", nozzle: 230 });
  });
});
