/* P7 校准运营：active bundle 导入、精确作用域匹配、估算展示与刷新持久化。 */
"use strict";

const { test, expect } = require("@playwright/test");

async function waitBooted(page) {
  await page.waitForFunction(() => window.FX && window.FX.sim && window.FX.sim.slice, null, {
    timeout: 30_000,
  });
}

function calibrationBundle() {
  return {
    format: "forgex-calibration-bundle",
    version: 1,
    id: "e2e-calibration",
    revision: 1,
    createdAt: "2026-07-28T00:00:00Z",
    provenance: "real-anonymized",
    source: {
      license: "CC0-1.0",
      note: "Playwright-only anonymized fixture for validating the browser calibration workflow.",
    },
    models: [
      {
        id: "e2e-fx-calibration-pla",
        status: "active",
        scope: {
          machineId: "FX-E2E-CAL",
          firmware: "Klipper 0.12",
          material: "PLA",
        },
        algorithm: "theil-sen",
        trainedAt: "2026-07-28T00:00:00Z",
        coefficients: {
          motionScale: 1.25,
          fixedOverheadSec: 15,
          sampleCount: 8,
        },
        validation: {
          holdoutSamples: 6,
          mape: 0.08,
          maxApe: 0.12,
          medianBias: 0.02,
          evaluatedAt: "2026-07-28T00:00:00Z",
        },
        thresholds: {
          maxMape: 0.2,
          maxBias: 0.12,
          minDriftSamples: 5,
        },
        trainingSetSha256: "a".repeat(64),
      },
    ],
  };
}

test.describe("P7 校准运营", () => {
  test("active 校准包按机型/固件/材料匹配并在刷新后保留", async ({ page }) => {
    await page.goto("/legacy");
    await waitBooted(page);

    const bundle = calibrationBundle();
    await page.locator("#calibration-input").setInputFiles({
      name: "e2e-calibration.json",
      mimeType: "application/json",
      buffer: Buffer.from(JSON.stringify(bundle)),
    });
    await page.waitForFunction(() => window.FXCalibrationRegistry.list().length === 1);

    await page.reload();
    await waitBooted(page);
    const persisted = await page.evaluate(() => window.FXCalibrationRegistry.list()[0]);
    expect(persisted.id).toBe("e2e-fx-calibration-pla");
    expect(persisted.status).toBe("active");

    const gcode = [
      "; generated by OrcaSlicer 2.2.0",
      "M83",
      "G90",
      "G28",
      "G1 Z0.20 F600",
      "G0 X20 Y20 F6000",
      ";TYPE:Outer wall",
      "G1 X80 Y20 E1 F600",
      "G1 X80 Y80 E1",
    ].join("\n");
    await page.locator("#gcode-input").setInputFiles({
      name: "p7-calibration.gcode",
      mimeType: "text/x-gcode",
      buffer: Buffer.from(gcode),
    });
    await page.waitForFunction(() => window.FX.sim.importedToolpath);

    await page.locator("#machine-log-input").setInputFiles({
      name: "p7-calibration.machine-log.json",
      mimeType: "application/json",
      buffer: Buffer.from(JSON.stringify({
        format: "forgex-machine-log",
        version: 1,
        job: {
          jobId: "P7-E2E-001",
          machineId: "FX-E2E-CAL",
          firmware: "Klipper 0.12",
          durationSec: 130,
          completedLayers: 1,
          status: "success",
        },
        telemetry: [],
      })),
    });

    await expect(page.locator("#machine-log-summary")).toContainText("e2e-fx-calibration-pla r1");
    await expect(page.locator("#machine-log-summary")).toContainText("holdout 区间");
    await expect(page.locator("#machine-log-summary")).toContainText("漂移 insufficient");
    const state = await page.evaluate(() => window.FX.ui._machineLogState.calibration);
    expect(state.estimate.predictedTimeSec).toBeGreaterThan(15);
    expect(state.estimate.lowerTimeSec).toBeLessThan(state.estimate.predictedTimeSec);
    expect(state.estimate.upperTimeSec).toBeGreaterThan(state.estimate.predictedTimeSec);
  });
});
