; generated by PrusaSlicer 2.8.1
; printer_model = FORGEX_VALIDATION
; estimated printing time (normal mode) = 3m 0s
; filament used [mm] = 7.2
M83
G28
G1 Z0.20 F720
G0 X10 Y10 F3600
;TYPE:External perimeter
G1 X110 Y10 E0.9 F600
G1 X110 Y110 E0.9
G1 X10 Y110 E0.9
G1 X10 Y10 E0.9
;LAYER_CHANGE
G1 Z0.40 F720
G0 X20 Y20 F3600
;TYPE:Solid infill
G1 X100 Y20 E0.9 F600
G1 X100 Y100 E0.9
G1 X20 Y100 E0.9
G1 X20 Y20 E0.9
