/* FORGE·X G-code 解析测试（node tests/gcode.test.js）

   最有力的一条是**往返一致性**：用本项目的导出器产出 G-code，再解析回来，
   统计量必须与原始切片数据对上。这同时验证了两端——
   解析器读错了会不一致，导出器写错了也会不一致，
   比单独给解析器喂几段手写片段强得多。

   其余用例覆盖各切片器的方言（Cura / PrusaSlicer / Orca 的注释格式与相对/绝对 E），
   以及「读不懂时如实报错而不是给个空结果」。 */
"use strict";
const path = require("path");
const J = (p) => path.join(__dirname, "..", "js", p);

require(J("util.js"));
require(J("slicer.js"));
require(J("models.js"));
require(J("exporter.js"));
require(J("gcode-parser.js"));

const FXSlicer = globalThis.FXSlicer,
  FXModels = globalThis.FXModels,
  FXExport = globalThis.FXExport,
  G = globalThis.FXGcodeParser;

let passed = 0,
  failed = 0;
function check(name, cond, detail) {
  if (cond) {
    passed++;
    console.log(`  PASS  ${name}`);
  } else {
    failed++;
    console.error(`  FAIL  ${name}${detail ? " — " + detail : ""}`);
  }
}
const near = (a, b, relTol) => Math.abs(a - b) <= Math.abs(b) * relTol;

const ST = {
  material: "PLA", layerHeight: 0.2, extrusionWidth: 0.45, perimeters: 2, solidLayers: 3,
  infillDensity: 0.18, nozzleTemp: 210, bedTemp: 60, speed: 120, travelSpeed: 260,
  retraction: 1.2, fanSpeed: 100, supportEnabled: true, supportSpacing: 4.5,
  skirtLoops: 2, skirtGap: 5, zOffset: 0, autoLevel: true,
};
const TF = { scale: 1, rotZ: 0, offX: 0, offY: 0 };

console.log("\n[1] 往返一致性：导出 → 解析 → 统计量必须对上");
const gear = FXModels.createBuiltins()[0];
const slice = FXSlicer.slice(gear, TF, ST);
const gcode = FXExport.gcode(slice, ST, { model: gear.name, printer: "FX-256", densityG: 1.24 });
const back = G.parse(gcode, { densityG: 1.24, bedSize: 256 });
{
  check("层数一致", back.totalLayers === slice.totalLayers, `${back.totalLayers} vs ${slice.totalLayers}`);
  check("成品高度一致（±1 层高）", Math.abs(back.height - slice.height) <= ST.layerHeight + 1e-6,
    `${back.height.toFixed(2)} vs ${slice.height.toFixed(2)}`);
  check("挤出路径总长一致（±1%）", near(back.stats.extLenMm, slice.stats.extLenMm, 0.01),
    `${back.stats.extLenMm.toFixed(1)} vs ${slice.stats.extLenMm.toFixed(1)}`);

  // 耗材长度：导出器按 ⌀1.75 折算 E，解析器再从 E 还原，两次换算必须闭合
  check("耗材长度一致（±1%）", near(back.stats.filamentM, slice.stats.filamentM, 0.01),
    `${back.stats.filamentM.toFixed(3)}m vs ${slice.stats.filamentM.toFixed(3)}m`);
  check("挤出体积一致（±1%）", near(back.stats.volumeCm3, slice.stats.volumeCm3, 0.01),
    `${back.stats.volumeCm3.toFixed(2)} vs ${slice.stats.volumeCm3.toFixed(2)}`);

  check("路径类型被保留（不是一律 infill）",
    new Set(back.layers.flatMap((L) => L.paths.map((p) => p.type))).size >= 3,
    [...new Set(back.layers.flatMap((L) => L.paths.map((p) => p.type)))].join(","));
  check("识别出周界与实心层",
    back.layers.some((L) => L.paths.some((p) => p.type === "perimeter")) &&
      back.layers.some((L) => L.paths.some((p) => p.type === "solid")));

  check("读出喷嘴与热床温度", back.claims.nozzleTemp === 210 && back.claims.bedTemp === 60,
    JSON.stringify({ n: back.claims.nozzleTemp, b: back.claims.bedTemp }));
  check("坐标居中回原点系（与切片同一坐标系）",
    Math.abs((back.bounds.minX + back.bounds.maxX) / 2) < 5,
    `中心 X ${((back.bounds.minX + back.bounds.maxX) / 2).toFixed(1)}`);
}

console.log("\n[2] 产出结构与 FXSlicer.slice() 同构（渲染层不必改一行）");
{
  const need = ["layers", "totalLayers", "height", "stats"];
  check("顶层字段齐全", need.every((k) => k in back), need.filter((k) => !(k in back)).join(","));
  const statKeys = ["extLenMm", "travelMm", "timeSec", "volumeCm3", "filamentM"];
  check("stats 字段齐全", statKeys.every((k) => typeof back.stats[k] === "number"),
    statKeys.filter((k) => typeof back.stats[k] !== "number").join(","));
  const L0 = back.layers[0];
  check("层结构含 z / paths", typeof L0.z === "number" && Array.isArray(L0.paths));
  const p0 = L0.paths[0];
  check("路径结构含 pts / type / len / speed",
    Array.isArray(p0.pts) && typeof p0.type === "string" &&
      typeof p0.len === "number" && typeof p0.speed === "number", JSON.stringify(Object.keys(p0)));
  check("路径点至少两个（单点无法成线）", back.layers.every((L) => L.paths.every((p) => p.pts.length >= 2)));
  check("路径长度与点序一致",
    back.layers.every((L) => L.paths.every((p) => {
      let s = 0;
      for (let i = 1; i < p.pts.length; i++) s += Math.hypot(p.pts[i].x - p.pts[i - 1].x, p.pts[i].y - p.pts[i - 1].y);
      return Math.abs(s - p.len) < 1e-6;
    })));
  check("每条路径保留真实 E 增量供回放记账",
    back.layers.every((L) => L.paths.every((p) => typeof p.filamentMm === "number" && p.filamentMm >= 0)));
}

console.log("\n[3] 切片器方言：绝对/相对 E、各家类型注释");
{
  // PrusaSlicer 风格：相对 E（M83）+ 「External perimeter」
  const prusa = [
    "; generated by PrusaSlicer 2.8.0",
    "; filament used [mm] = 1000",
    "M83",
    "G21", "G90", "G28",
    "G1 Z0.2 F720",
    ";TYPE:External perimeter",
    "G1 F1800 X100 Y100 E0",
    "G1 X110 Y100 E0.5",
    "G1 X110 Y110 E0.5",
    ";TYPE:Solid infill",
    "G1 X100 Y110 E0.5",
  ].join("\n");
  const rp = G.parse(prusa, { bedSize: 256 });
  check("PrusaSlicer 相对 E 解析正确（3 段各 0.5 = 1.5）",
    near(rp.stats.filamentM * 1000, 1.5, 0.01), String(rp.stats.filamentM * 1000));
  check("识别 External perimeter → perimeter",
    rp.layers[0].paths.some((p) => p.type === "perimeter"),
    rp.layers[0].paths.map((p) => p.type).join(","));
  check("识别 Solid infill → solid", rp.layers[0].paths.some((p) => p.type === "solid"));
  check("读出切片器名", /PrusaSlicer/.test(rp.claims.slicer || ""), rp.claims.slicer);
  check("读出自报耗材长度", rp.claims.filamentMm === 1000, String(rp.claims.filamentMm));

  // Cura 风格：绝对 E（M82）+ 「WALL-OUTER」+ ;TIME:
  const cura = [
    ";Generated with Cura_SteamEngine 5.7.0",
    ";TIME:3600",
    ";Filament used: 2.5m",
    "M82",
    "G28",
    "G1 Z0.2",
    ";TYPE:WALL-OUTER",
    "G1 F1800 X100 Y100 E0",
    "G1 X120 Y100 E1.0",
    ";TYPE:FILL",
    "G1 X120 Y120 E2.0",
  ].join("\n");
  const rc = G.parse(cura, { bedSize: 256 });
  check("Cura 绝对 E 解析正确（累计到 2.0）", near(rc.stats.filamentM * 1000, 2.0, 0.01),
    String(rc.stats.filamentM * 1000));
  check("识别 WALL-OUTER → perimeter", rc.layers[0].paths.some((p) => p.type === "perimeter"));
  check("识别 FILL → infill", rc.layers[0].paths.some((p) => p.type === "infill"));
  check("读出自报时长 3600s", rc.claims.timeSec === 3600, String(rc.claims.timeSec));
  check("读出自报耗材 2.5m → 2500mm", rc.claims.filamentMm === 2500, String(rc.claims.filamentMm));

  const flavored = G.parse(
    [";FLAVOR:Marlin", "M83", "G28", "G1 Z0.2", "G1 X10 Y10 E0", "G1 X20 Y10 E0.5"].join("\n"),
    { bedSize: 256 }
  );
  check("读出 Cura FLAVOR 固件声明", flavored.claims.firmware === "Marlin", flavored.claims.firmware);

  // G92 E0 归零（每层重置 E 的切片器）
  const g92 = [
    "M82", "G28", "G1 Z0.2",
    "G1 X100 Y100 E0", "G1 X110 Y100 E1.0",
    "G92 E0",
    "G1 X110 Y110 E1.0",
  ].join("\n");
  const r92 = G.parse(g92, { bedSize: 256 });
  check("G92 E0 归零后不产生负增量", near(r92.stats.filamentM * 1000, 2.0, 0.01),
    String(r92.stats.filamentM * 1000));

  // 相对坐标 G91
  const rel = ["M83", "G28", "G1 Z0.2", "G90", "G1 X100 Y100", "G91", "G1 X10 E0.5", "G1 Y10 E0.5"].join("\n");
  const rr = G.parse(rel, { bedSize: 256 });
  check("G91 相对坐标位移正确（10+10=20mm）", near(rr.stats.extLenMm, 20, 0.01), String(rr.stats.extLenMm));
}

console.log("\n[4] 空驶与回抽不计入挤出");
{
  const gc = [
    "M83", "G28", "G1 Z0.2",
    "G1 X100 Y100 E0",
    "G1 F1800 X110 Y100 E0.5",     // 挤出 10mm
    "G1 E-1.2 F2400",              // 回抽（无位移）
    "G0 F9000 X150 Y150",          // 空驶 ~57mm
    "G1 E1.2 F2400",               // 回填
    "G1 F1800 X160 Y150 E0.5",     // 挤出 10mm
  ].join("\n");
  const r = G.parse(gc, { bedSize: 256 });
  check("挤出总长只算挤出段（20mm）", near(r.stats.extLenMm, 20, 0.01), String(r.stats.extLenMm));
  check("空驶长度单独统计", r.stats.travelMm > 50, String(r.stats.travelMm));
  check("回抽/回填互相抵消，净耗材为 1.0", near(r.stats.filamentM * 1000, 1.0, 0.02),
    String(r.stats.filamentM * 1000));
  check("空驶把路径断开（不会连成一条）", r.layers[0].paths.length === 2,
    String(r.layers[0].paths.length));
}

console.log("\n[5] 对账：与切片器自报数字并列，但不判谁对");
{
  const rec = G.reconcile(back);
  check("往返数据无自报字段时对账表为空或仅含温度类", Array.isArray(rec));

  const withClaims = G.parse(
    [";TIME:100", "; Filament used: 0.002m", "M83", "G28", "G1 Z0.2",
     "G1 X100 Y100 E0", "G1 F1200 X110 Y100 E2.0"].join("\n"), { bedSize: 256 });
  const r2 = G.reconcile(withClaims);
  check("对账表列出时长与耗材两项", r2.length >= 2, JSON.stringify(r2.map((x) => x.name)));
  const t = r2.find((x) => x.name === "打印时长");
  check("对账项含自报值与重算值", t && t.claimed === 100 && t.computed > 0,
    JSON.stringify(t && { c: t.claimed, k: t.computed }));
  check("对账项给出相对差与是否吻合", t && typeof t.relDiff === "number" && typeof t.agrees === "boolean");
  check("对账项附带解释（差异不等于谁错）", t && /加速度|正常/.test(t.note), t && t.note);
  const fl = r2.find((x) => x.name === "耗材长度");
  check("耗材长度对账吻合（都来自 E 值）", fl && fl.agrees === true,
    fl && `${fl.claimed} vs ${fl.computed.toFixed(2)}`);
}

console.log("\n[6] 读不懂时如实报错，不给空结果");
{
  let err = null;
  try { G.parse("这不是 G-code\n随便写点什么"); } catch (e) { err = e; }
  check("非 G-code 文本 → 抛错而非返回空", !!err && /挤出路径/.test(err.message), err && err.message);

  err = null;
  try { G.parse(""); } catch (e) { err = e; }
  check("空文件 → 抛错", !!err);

  err = null;
  try { G.parse("G28\nG1 X10 Y10 F1200\nG1 X20 Y20"); } catch (e) { err = e; }
  check("只有空驶没有挤出 → 抛错（不是有效打印件）", !!err, err && err.message);

  err = null;
  try { G.parse("x".repeat(G.MAX_BYTES + 1)); } catch (e) { err = e; }
  check("超大文件 → 明确报错而非卡死", !!err && /MB/.test(err.message), err && err.message);
}

console.log("\n[7] 警告：如实说明近似与异常，不静默");
{
  const noHome = G.parse(["M83", "G1 Z0.2", "G1 X100 Y100 E0", "G1 X110 Y100 E0.5"].join("\n"), { bedSize: 256 });
  check("缺 G28 时警告", noHome.warnings.some((w) => /归位/.test(w)), noHome.warnings.join("|"));

  const arcs = G.parse(
    ["M83", "G28", "G1 Z0.2", "G1 X100 Y100 E0", "G2 X110 Y100 I5 J0 E0.5", "G1 X120 Y100 E0.5"].join("\n"),
    { bedSize: 256 });
  check("含圆弧指令时如实说明按直线近似",
    arcs.warnings.some((w) => /圆弧/.test(w)), arcs.warnings.join("|"));

  const oversize = G.parse(
    ["M83", "G28", "G1 Z0.2", "G1 X0 Y0 E0", "G1 X400 Y400 E5"].join("\n"), { bedSize: 256 });
  check("超出打印床时警告", oversize.warnings.some((w) => /打印床/.test(w)), oversize.warnings.join("|"));

  check("正常文件不产生无谓警告", back.warnings.length === 0, back.warnings.join("|"));

  const centered = G.parse(
    ["M83", "G28", "G1 Z0.2", "G1 X-10 Y0 E0", "G1 X10 Y0 E1"].join("\n"),
    { bedSize: 260, origin: "center" });
  check("中心原点机型不重复平移坐标",
    centered.bounds.minX === -10 && centered.bounds.maxX === 10 &&
      centered.coordinateOrigin === "center",
    JSON.stringify(centered.bounds));
}

console.log("\n[8] 挤出量来自 E 的真实增量，而非路径长估算");
{
  // 同样的路径长度，故意给两倍的 E —— 体积必须跟着 E 走
  const thin = G.parse(["M83", "G28", "G1 Z0.2", "G1 X100 Y100 E0", "G1 X110 Y100 E1.0"].join("\n"), { bedSize: 256 });
  const thick = G.parse(["M83", "G28", "G1 Z0.2", "G1 X100 Y100 E0", "G1 X110 Y100 E2.0"].join("\n"), { bedSize: 256 });
  check("路径长相同", near(thin.stats.extLenMm, thick.stats.extLenMm, 1e-9));
  check("E 翻倍 → 体积翻倍（证明不是按路径长估算）",
    near(thick.stats.volumeCm3, thin.stats.volumeCm3 * 2, 1e-6),
    `${thin.stats.volumeCm3.toExponential(3)} → ${thick.stats.volumeCm3.toExponential(3)}`);
  check("克重随材料密度变化",
    G.parse(["M83", "G28", "G1 Z0.2", "G1 X100 Y100 E0", "G1 X110 Y100 E1.0"].join("\n"),
      { densityG: 2.48, bedSize: 256 }).stats.filamentG > thin.stats.filamentG * 1.9);
}

console.log(`\n═══ 结果：${passed} 通过 / ${failed} 失败 ═══`);
process.exit(failed ? 1 : 0);
