using System.Text.Json;
using ForgeX.Analytics;

namespace ForgeX.ResourceGate;

/// <summary>JsJson / DatasetProvenanceSanitizer / Bm25Retrieval versus fixtures generated by the Node runtime.</summary>
internal static class ParitySection
{
    public static void Run(Gate gate)
    {
        gate.Section("parity: JsJson / provenance / BM25 vs Node fixtures");
        var parity = Gate.Fixture("resource-parity.json");

        foreach (var item in parity.GetProperty("stringify").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var actual = JsJson.Stringify(item.GetProperty("input"));
            gate.Check($"parity-stringify-{name}", actual == item.GetProperty("expected").GetString(), actual);
        }

        // JSON.stringify("\ud800x\udc00") === "\"\\ud800x\\udc00\""：孤立代理项转义为小写 \uXXXX，
        // 成对代理项原样输出。STJ 无法承载孤立代理项的 JSON 文本，因此这一条不走夹具。
        gate.Check("parity-stringify-lone-surrogate-literal",
            JsJson.EscapeString("\ud800x\udc00") == "\"\\ud800x\\udc00\"" && JsJson.EscapeString("😀") == "\"😀\"",
            JsJson.EscapeString("\ud800x\udc00"));

        foreach (var item in parity.GetProperty("stable").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var actual = JsJson.Stable(item.GetProperty("input"));
            gate.Check($"parity-stable-{name}", actual == item.GetProperty("expected").GetString(), actual);
            var digest = JsJson.Sha256Hex(actual);
            gate.Check($"parity-digest-{name}", digest == item.GetProperty("digest").GetString(), digest);
        }

        foreach (var item in parity.GetProperty("provenance").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var claim = item.GetProperty("claim");
            var actual = JsJson.Stringify(DatasetProvenanceSanitizer.Sanitize(claim.ValueKind == JsonValueKind.Null ? null : claim));
            gate.Check($"parity-provenance-{name}", actual == item.GetProperty("expectedStringify").GetString(), actual);
        }

        foreach (var item in parity.GetProperty("tokenize").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var actual = JsonSerializer.Serialize(Bm25Retrieval.Tokenize(item.GetProperty("input").GetString()));
            var expected = JsonSerializer.Serialize(item.GetProperty("expected").EnumerateArray().Select(static t => t.GetString()).ToArray());
            gate.Check($"parity-tokenize-{name}", actual == expected, actual);
        }

        foreach (var item in parity.GetProperty("chunk").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var actual = JsonSerializer.Serialize(Bm25Retrieval.Chunk(item.GetProperty("input").GetString(), item.GetProperty("maxLen").GetInt32()));
            var expected = JsonSerializer.Serialize(item.GetProperty("expected").EnumerateArray().Select(static t => t.GetString()).ToArray());
            gate.Check($"parity-chunk-{name}", actual == expected, actual);
        }

        foreach (var item in parity.GetProperty("retrieve").EnumerateArray())
        {
            var name = item.GetProperty("name").GetString();
            var docs = item.GetProperty("docs").EnumerateArray()
                .Select(static doc => new RetrievalDocument(
                    doc.GetProperty("id").GetString()!,
                    doc.GetProperty("name").GetString()!,
                    doc.GetProperty("text").GetString()!))
                .ToList();
            var topKElement = item.GetProperty("topK");
            var topK = topKElement.ValueKind == JsonValueKind.Null ? Bm25Retrieval.DefaultTopK : topKElement.GetInt32();
            var hits = Bm25Retrieval.Retrieve(docs, item.GetProperty("question").GetString(), topK);
            var actual = string.Join("|", hits.Select(static hit => $"{hit.Name}\u0001{hit.Text}\u0001{JsFormat.Number(hit.Score)}"));
            var expected = string.Join("|", item.GetProperty("expected").EnumerateArray()
                .Select(static hit => $"{hit.GetProperty("name").GetString()}\u0001{hit.GetProperty("text").GetString()}\u0001{hit.GetProperty("score").GetRawText()}"));
            gate.Check($"parity-retrieve-{name}", actual == expected, actual);
        }

        var identity = parity.GetProperty("datasourceIdentity");
        var csv = identity.GetProperty("csv").GetString()!;
        var contentSha256 = JsJson.Sha256Hex(csv);
        gate.Check("parity-datasource-content-sha256", contentSha256 == identity.GetProperty("contentSha256").GetString(), contentSha256);
        var provenance = DatasetProvenanceSanitizer.Sanitize(JsonDocument.Parse("{\"synthetic\":true,\"badge\":\"机群\"}").RootElement.Clone());
        var cacheKey = JsJson.Sha256Hex(contentSha256 + "\0" + JsJson.Stringify(provenance));
        gate.Check("parity-datasource-cache-key", cacheKey == identity.GetProperty("cacheKey").GetString(), cacheKey);
        var id = "ds_" + JsJson.Sha256Hex(identity.GetProperty("tenantId").GetString() + "\0" + cacheKey)[..24];
        gate.Check("parity-datasource-id", id == identity.GetProperty("id").GetString(), id);
    }
}
