/* Stage 10.3 Worker 收口的结构卡口：
   1) ParsedGcodeResult → TypedArray 打包 → 分片重建，必须与 parse() 原始输出完全同构——
      这是 Worker 边界上唯一的自定义序列化逻辑，漂移会静默破坏渲染/导出/对账全链；
   2) buildToolpathBuffers 的 stride 采样与旧 attachToolpath 内联实现逐值一致
      （float32 舍入后），保证 Worker 预计算的顶点缓冲与主线程就地构建不可区分。 */
import { describe, expect, it } from "vitest";
import { parse, type ParsedGcodeResult } from "../../engine/gcode-parser";
import { buildToolpathBuffers, type ToolpathLayerLike } from "../../engine/toolpath-buffers";
import { packParsedGcode, packedGcodeTransferables, unpackParsedGcode } from "./gcode-toolpath-pack";

/** 多层多类型 + 回抽/空驶 + 声明注释；刻意不写 G28 以携带 warnings，覆盖 meta 克隆面 */
function fixtureGcode(layers: number): string {
  const lines: string[] = [";TIME:360", ";Filament used: 0.9m", "; generated by Cura_SteamEngine 5.10", "G90", "M82"];
  let e: number;
  for (let layer = 0; layer < layers; layer++) {
    const z = (0.2 * (layer + 1)).toFixed(2);
    lines.push(`;LAYER:${layer}`, "G92 E0", `G1 Z${z} F600`);
    e = 0;
    lines.push(";TYPE:WALL-OUTER");
    lines.push("G0 X10 Y10 F6000");
    for (let i = 1; i <= 8; i++) {
      e += 0.4;
      lines.push(`G1 X${10 + i * 3} Y${10 + ((i * 7) % 11)} E${e.toFixed(4)} F1350`);
    }
    lines.push(";TYPE:FILL");
    for (let strip = 0; strip < 3; strip++) {
      e -= 0.8;
      lines.push(`G1 E${e.toFixed(4)} F2700`);
      lines.push(`G0 X${12 + strip} Y${20 + strip * 2} F9000`);
      e += 0.8;
      lines.push(`G1 E${e.toFixed(4)} F2700`);
      for (let i = 1; i <= 4; i++) {
        e += 0.25;
        lines.push(`G1 X${12 + strip + i * 5} Y${20 + strip * 2} E${e.toFixed(4)} F2400`);
      }
    }
  }
  return lines.join("\n") + "\n";
}

describe("G-code 打包往返（Worker 边界序列化卡口）", () => {
  const parsed = parse(fixtureGcode(6), { densityG: 1.24, bedSize: 256, origin: "corner" });

  it("pack → unpack 与 parse() 输出完全同构", async () => {
    const packed = packParsedGcode(parsed);
    const rebuilt = await unpackParsedGcode(packed);
    expect(rebuilt).toEqual(parsed);
    // 关键截面显式复核（toEqual 之外再锁一遍量级，防 fixture 退化成空集）
    expect(rebuilt.totalLayers).toBe(6);
    expect(rebuilt.layers.reduce((n, l) => n + l.paths.length, 0)).toBeGreaterThan(20);
    expect(rebuilt.warnings.length).toBeGreaterThan(0); // 无 G28 → 归位警告必须原样穿透
  });

  it("分片重建（强制多次让出）结果不变，且确实发生让出", async () => {
    const packed = packParsedGcode(parsed);
    let yields = 0;
    const rebuilt = await unpackParsedGcode(packed, {
      pointsPerSlice: 8,
      yieldToEventLoop: () => {
        yields += 1;
        return Promise.resolve();
      },
    });
    expect(rebuilt).toEqual(parsed);
    expect(yields).toBeGreaterThan(5);
  });

  it("transfer 清单覆盖全部 TypedArray 底层 buffer", () => {
    const packed = packParsedGcode(parsed);
    const transfer = packedGcodeTransferables(packed);
    expect(transfer).toHaveLength(7);
    expect(new Set(transfer).size).toBe(7);
    expect(transfer).toContain(packed.coords.buffer);
    expect(transfer).toContain(packed.pathStats.buffer);
  });

  it("len 缺省的路径按 NaN 哨兵穿透后仍缺省", async () => {
    const minimal: ParsedGcodeResult = {
      layers: [
        {
          z: 0.2,
          paths: [
            {
              pts: [
                { x: 0, y: 0 },
                { x: 3, y: 4 },
              ],
              type: "perimeter",
              speed: 30,
              filamentMm: 0.2,
            },
          ],
          extLen: 5,
          travelLen: 0,
          timeSec: 0.5,
        },
      ],
      totalLayers: 1,
      height: 0.2,
      stats: { extLenMm: 5, travelMm: 0, timeSec: 0.5, volumeCm3: 0.001, filamentM: 0.0002, filamentG: 0.0012 },
      claims: {},
      warnings: [],
      bounds: { minX: 0, maxX: 3, minY: 0, maxY: 4 },
      coordinateOrigin: "corner",
      source: "gcode-import",
    };
    const rebuilt = await unpackParsedGcode(packParsedGcode(minimal));
    expect(rebuilt).toEqual(minimal);
    expect("len" in rebuilt.layers[0]!.paths[0]!).toBe(false);
  });
});

/** 旧 attachToolpath 内联采样的逐行参考实现（number[] 版），作为一致性基准 */
function referenceBuffers(layers: readonly ToolpathLayerLike[], maxSegments: number) {
  let totalSegments = 0;
  for (const layer of layers) for (const path of layer.paths) totalSegments += Math.max(0, path.pts.length - 1);
  const stride = Math.max(1, Math.ceil(totalSegments / maxSegments));
  const positions: number[] = [];
  const ranges: Array<{ z: number; count: number }> = [];
  let seen = 0;
  for (const layer of layers) {
    for (const path of layer.paths) {
      for (let i = 1; i < path.pts.length; i++) {
        if (seen % stride === 0) {
          const a = path.pts[i - 1]!;
          const b = path.pts[i]!;
          positions.push(a.x, layer.z, -a.y, b.x, layer.z, -b.y);
        }
        seen++;
      }
    }
    ranges.push({ z: layer.z, count: positions.length / 3 });
  }
  return { positions, ranges, stride };
}

describe("toolpath 顶点缓冲构建（与旧 attachToolpath 内联实现一致）", () => {
  const parsed = parse(fixtureGcode(5), { densityG: 1.24, bedSize: 256, origin: "corner" });

  it("stride = 1：全量段逐 float32 一致，ranges 逐层累计一致", () => {
    const built = buildToolpathBuffers(parsed.layers);
    const reference = referenceBuffers(parsed.layers, 400000);
    expect(built.stride).toBe(1);
    expect(built.positions.length).toBe(reference.positions.length);
    for (let i = 0; i < reference.positions.length; i++) {
      expect(built.positions[i]).toBe(Math.fround(reference.positions[i]!));
    }
    expect(built.ranges).toEqual(reference.ranges);
  });

  it("stride > 1：抽稀采样与参考实现一致", () => {
    const built = buildToolpathBuffers(parsed.layers, 16);
    const reference = referenceBuffers(parsed.layers, 16);
    expect(built.stride).toBe(reference.stride);
    expect(built.stride).toBeGreaterThan(1);
    expect(built.positions.length).toBe(reference.positions.length);
    for (let i = 0; i < reference.positions.length; i++) {
      expect(built.positions[i]).toBe(Math.fround(reference.positions[i]!));
    }
    expect(built.ranges).toEqual(reference.ranges);
  });

  it("空输入产出空缓冲（挂载层据此跳过 THREE 装配）", () => {
    const built = buildToolpathBuffers([]);
    expect(built.positions.length).toBe(0);
    expect(built.ranges).toEqual([]);
    expect(built.stride).toBe(1);
  });
});
