/* 录制 P5 的约 90 秒无声产品演示。
 * 需要开发依赖中的 Playwright；输出 WebM，讲解词见 doc/demo-script.md。 */
/* global window, document */
"use strict";

const fs = require("fs");
const path = require("path");
const { chromium } = require("@playwright/test");

const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.resolve(process.argv[2] || path.join(ROOT, "doc", "assets", "forgex-p5-demo.webm"));
const TEMP = path.join(ROOT, "test-results", "demo-video");

function demoGcode() {
  const lines = [
    "; generated by Cura_SteamEngine 5.10",
    ";TIME:580",
    ";Filament used: 0.012m",
    "G21",
    "G90",
    "M83",
    "G28",
    "M104 S215",
    "M140 S60",
  ];
  for (let layer = 0; layer < 50; layer++) {
    const z = ((layer + 1) * 0.2).toFixed(2);
    const inset = Math.min(8, layer * 0.08);
    const a = (108 + inset).toFixed(2);
    const b = (148 - inset).toFixed(2);
    lines.push(
      `;LAYER:${layer}`,
      `G1 Z${z} F720`,
      `G0 X${a} Y${a} F6000`,
      ";TYPE:WALL-OUTER",
      `G1 X${b} Y${a} E0.42 F1800`,
      `G1 X${b} Y${b} E0.42`,
      `G1 X${a} Y${b} E0.42`,
      `G1 X${a} Y${a} E0.42`,
      ";TYPE:FILL",
      `G1 X${b} Y${b} E0.55 F2400`
    );
  }
  return lines.join("\n");
}

function demoProfile() {
  return {
    format: "forgex-profile-bundle",
    version: 1,
    machines: [
      {
        id: "demo-corexy-300",
        name: "Demo CoreXY 300",
        tag: "DEMO-300",
        kinematics: "corexy",
        description: "Community profile · enclosed 300mm",
        buildVolume: { x: 300, y: 300, z: 300 },
        enclosed: true,
        physics: { heaterHealth: 0.97, beltWear: 0.06, ambientC: 29, draft: 0.08 },
        source: "FORGE·X recorded demo fixture",
      },
    ],
    materials: [
      {
        id: "PLA-HF-demo",
        name: "PLA-HF Demo",
        nozzle: { default: 220, min: 210, max: 230 },
        bed: { default: 60, min: 55 },
        fan: 100,
        densityG: 1.24,
        maxSpeed: 350,
        flowMm3s: 18,
        shrinkage: 0.25,
        priceCnyKg: 99,
        source: "FORGE·X recorded demo fixture",
      },
    ],
  };
}

async function main() {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.mkdirSync(TEMP, { recursive: true });
  const browser = await chromium.launch({
    headless: true,
    args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--disable-gpu-sandbox"],
  });
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    recordVideo: { dir: TEMP, size: { width: 1280, height: 720 } },
  });
  const page = await context.newPage();
  const fileUrl = "file:///" + path.join(ROOT, "index.html").replace(/\\/g, "/");
  await page.goto(fileUrl);
  await page.waitForFunction(() => window.FX && window.FX.sim && window.FX.sim.slice, null, {
    timeout: 30000,
  });

  await page.evaluate(() => {
    const box = document.createElement("div");
    box.id = "demo-caption";
    box.style.cssText = [
      "position:fixed",
      "left:50%",
      "bottom:92px",
      "transform:translateX(-50%)",
      "z-index:99999",
      "max-width:880px",
      "padding:14px 22px",
      "border-radius:14px",
      "background:rgba(18,22,30,.88)",
      "color:#f5f7fb",
      "font:600 20px/1.45 sans-serif",
      "letter-spacing:.02em",
      "box-shadow:0 12px 40px rgba(0,0,0,.28)",
      "backdrop-filter:blur(12px)",
      "text-align:center",
    ].join(";");
    document.body.appendChild(box);
  });
  const caption = (text) =>
    page.evaluate((value) => {
      document.querySelector("#demo-caption").textContent = value;
    }, text);
  const hold = (ms) => page.waitForTimeout(ms);
  const started = Date.now();

  await caption("从模型与切片，到真实 G-code 复盘与生产洞察");
  await page.locator('#hud-cam button[data-v="overview"]').click();
  await hold(7000);

  await caption("导入真实切片器 G-code：路径、层、速度与 E 增量全部保留");
  await page.locator("#gcode-input").setInputFiles({
    name: "forgex-demo.gcode",
    mimeType: "text/x-gcode",
    buffer: Buffer.from(demoGcode()),
  });
  await page.waitForFunction(() => window.FX.sim.importedToolpath);
  await hold(9000);

  await caption("任意层可在 2D / 3D 中同步检查");
  await page.locator("#flow-pills .flow-pill", { hasText: "切片" }).click();
  await page.waitForSelector("#ctx-body input[type=range]");
  await page.locator("#ctx-body input[type=range]").first().fill("25");
  await hold(10000);

  await caption("切片器自报值与本地重算并列，不隐藏口径差异");
  await page.locator("#flow-pills .flow-pill", { hasText: "模型" }).click();
  await hold(7000);

  await caption("追加真机日志：比较计划与实际时长、耗材和完成层数");
  await page.locator("#machine-log-input").setInputFiles({
    name: "forgex-demo-machine-log.json",
    mimeType: "application/json",
    buffer: Buffer.from(
      JSON.stringify({
        format: "forgex-machine-log",
        version: 1,
        job: {
          jobId: "DEMO-001",
          durationSec: 720,
          filamentMm: 12,
          completedLayers: 50,
          status: "success",
        },
        telemetry: [
          { timeSec: 0, nozzleC: 25, bedC: 25 },
          { timeSec: 90, nozzleC: 214.6, bedC: 59.4 },
          { timeSec: 720, nozzleC: 212.8, bedC: 58.9 },
        ],
      })
    ),
  });
  await page.waitForSelector("#machine-log-summary");
  await hold(10000);

  await caption("声明式 Profile 扩展机器与材料，schema 和白名单守住边界");
  await page.locator("#profile-input").setInputFiles({
    name: "forgex-demo-profile.json",
    mimeType: "application/json",
    buffer: Buffer.from(JSON.stringify(demoProfile())),
  });
  await page.waitForFunction(() => window.FXProfiles.machine("demo-corexy-300"));
  await page.evaluate(() => {
    window.FX.sim.setPrinterModel("demo-corexy-300");
    window.FX.ui.renderCtx("import");
  });
  await hold(9000);

  await caption("同一份真实路径进入预热、调平、沉积与实时遥测");
  await page.locator('#speed-seg button[data-v="8"]').click();
  await page.locator("#btn-start").click();
  await hold(16000);

  await caption("从一条路径到机群结论，来源与统计证据始终跟随结果");
  await page.locator("#pill-insight").click();
  await hold(9000);

  const remaining = 90000 - (Date.now() - started);
  if (remaining > 0) await hold(remaining);
  await caption("FORGE·X Insight · Observable, reproducible, explainable");
  await hold(2500);

  const video = page.video();
  await page.close();
  await video.saveAs(OUTPUT);
  await context.close();
  await browser.close();
  console.log(`Demo video saved: ${OUTPUT}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
